// SQL Notebook
// Copyright (C) 2018 Brian Luft
//
// Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
// documentation files (the "Software"), to deal in the Software without restriction, including without limitation the
// rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the Software, and to
// permit persons to whom the Software is furnished to do so, subject to the following conditions:
//
// The above copyright notice and this permission notice shall be included in all copies or substantial portions of the
// Software.
//
// THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE
// WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS
// OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR
// OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

namespace SqlNotebook.Interpreter.Tokens {
    // generate this list from the sqlite source code using:
    // cat ext/sqlite/sqlite3.c | grep "#define TK_" | awk '{ print $2 " = " $3 "," }' | sed "s/^TK_//g"
    public enum TokenKind {
        SEMI = 1,
        EXPLAIN = 2,
        QUERY = 3,
        PLAN = 4,
        BEGIN = 5,
        TRANSACTION = 6,
        DEFERRED = 7,
        IMMEDIATE = 8,
        EXCLUSIVE = 9,
        COMMIT = 10,
        END = 11,
        ROLLBACK = 12,
        SAVEPOINT = 13,
        RELEASE = 14,
        TO = 15,
        TABLE = 16,
        CREATE = 17,
        IF = 18,
        NOT = 19,
        EXISTS = 20,
        TEMP = 21,
        LP = 22,
        RP = 23,
        AS = 24,
        WITHOUT = 25,
        COMMA = 26,
        OR = 27,
        AND = 28,
        IS = 29,
        MATCH = 30,
        LIKE_KW = 31,
        BETWEEN = 32,
        IN = 33,
        ISNULL = 34,
        NOTNULL = 35,
        NE = 36,
        EQ = 37,
        GT = 38,
        LE = 39,
        LT = 40,
        GE = 41,
        ESCAPE = 42,
        BITAND = 43,
        BITOR = 44,
        LSHIFT = 45,
        RSHIFT = 46,
        PLUS = 47,
        MINUS = 48,
        STAR = 49,
        SLASH = 50,
        REM = 51,
        CONCAT = 52,
        COLLATE = 53,
        BITNOT = 54,
        ID = 55,
        INDEXED = 56,
        ABORT = 57,
        ACTION = 58,
        AFTER = 59,
        ANALYZE = 60,
        ASC = 61,
        ATTACH = 62,
        BEFORE = 63,
        BY = 64,
        CASCADE = 65,
        CAST = 66,
        COLUMNKW = 67,
        CONFLICT = 68,
        DATABASE = 69,
        DESC = 70,
        DETACH = 71,
        EACH = 72,
        FAIL = 73,
        FOR = 74,
        IGNORE = 75,
        INITIALLY = 76,
        INSTEAD = 77,
        NO = 78,
        KEY = 79,
        OF = 80,
        OFFSET = 81,
        PRAGMA = 82,
        RAISE = 83,
        RECURSIVE = 84,
        REPLACE = 85,
        RESTRICT = 86,
        ROW = 87,
        TRIGGER = 88,
        VACUUM = 89,
        VIEW = 90,
        VIRTUAL = 91,
        WITH = 92,
        REINDEX = 93,
        RENAME = 94,
        CTIME_KW = 95,
        ANY = 96,
        STRING = 97,
        JOIN_KW = 98,
        CONSTRAINT = 99,
        DEFAULT = 100,
        NULL = 101,
        PRIMARY = 102,
        UNIQUE = 103,
        CHECK = 104,
        REFERENCES = 105,
        AUTOINCR = 106,
        ON = 107,
        INSERT = 108,
        DELETE = 109,
        UPDATE = 110,
        SET = 111,
        DEFERRABLE = 112,
        FOREIGN = 113,
        DROP = 114,
        UNION = 115,
        ALL = 116,
        EXCEPT = 117,
        INTERSECT = 118,
        SELECT = 119,
        VALUES = 120,
        DISTINCT = 121,
        DOT = 122,
        FROM = 123,
        JOIN = 124,
        USING = 125,
        ORDER = 126,
        GROUP = 127,
        HAVING = 128,
        LIMIT = 129,
        WHERE = 130,
        INTO = 131,
        INTEGER = 132,
        FLOAT = 133,
        BLOB = 134,
        VARIABLE = 135,
        CASE = 136,
        WHEN = 137,
        THEN = 138,
        ELSE = 139,
        INDEX = 140,
        ALTER = 141,
        ADD = 142,
        TO_TEXT = 143,
        TO_BLOB = 144,
        TO_NUMERIC = 145,
        TO_INT = 146,
        TO_REAL = 147,
        ISNOT = 148,
        END_OF_FILE = 149,
        UNCLOSED_STRING = 150,
        FUNCTION = 151,
        COLUMN = 152,
        AGG_FUNCTION = 153,
        AGG_COLUMN = 154,
        UMINUS = 155,
        UPLUS = 156,
        REGISTER = 157,
        ASTERISK = 158,
        SPAN = 159,
        SPACE = 160,
        ILLEGAL = 161
    }
}
